name: 'Setup TinyGo environment'
description: 'Setup a TinyGo environment and add it to the PATH'
inputs:
  version:
    description: 'The Go version to download and use. Must be a valid commitish, e.g. "dev" or "v1.0.0"'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install LLVM 13
      run: |
        source /etc/os-release
        echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-13 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get -qq update
        sudo apt-get -yqq install clang-13 llvm-13-dev lld-13 libclang-13-dev
      shell: bash

    - uses: actions/setup-go@v5
      with:
        go-version: 1.18

    - name: Install Binaryen
      run: |
        pushd /dev/shm
        VERSION="$(curl -fsSLI -o /dev/null -w "%{url_effective}" https://github.com/WebAssembly/binaryen/releases/latest)"
        VERSION="${VERSION#https://github.com/WebAssembly/binaryen/releases/tag/}"
        curl -sfOL "https://github.com/WebAssembly/binaryen/releases/download/${VERSION}/binaryen-${VERSION}-$(uname -m)-linux.tar.gz"
        tar -xvf "binaryen-${VERSION}-$(uname -m)-linux.tar.gz"
        mkdir -p "${RUNNER_TOOL_CACHE}/binaryen"
        mv "binaryen-${VERSION}" "${RUNNER_TOOL_CACHE}/binaryen/${VERSION}"
        echo "${RUNNER_TOOL_CACHE}/binaryen/${VERSION}/bin" >> $GITHUB_PATH
        popd
      shell: bash

    - name: Install TinyGo
      run: |
        pushd /dev/shm
        mkdir tinygo
        cd tinygo
        git init
        git remote add origin https://github.com/tinygo-org/tinygo.git
        git fetch --prune --progress --no-tags --depth=1 origin "${{ inputs.version }}"
        git checkout --progress --force -B "${{ inputs.version }}" FETCH_HEAD
        git submodule update --init --recursive --depth 1
        make wasi-libc
        mkdir -p "${RUNNER_TOOL_CACHE}/tinygo/${{ inputs.version }}"
        GOBIN="${RUNNER_TOOL_CACHE}/tinygo/${{ inputs.version }}" go install
        echo "${RUNNER_TOOL_CACHE}/tinygo/${{ inputs.version }}" >> $GITHUB_PATH
        popd
      shell: bash
